#!/bin/bash -e
COLOR_SET="#[fg=cyan bg=magenta bold]"
COLOR_RESET="#[fg=$BYOBU_LIGHT bg=$BYOBU_DARK]"
REMIND_COMMAND="rem"
REMINDCOUNT=$(($($REMIND_COMMAND | grep . | wc -l)-1))
if [ $REMINDCOUNT = 0 ]; then
    exit 0
fi
echo "$COLOR_SET""$REMINDCOUNT"R"$COLOR_RESET"
exit 0

